### PR TITLE
Fix: Boolean values

### PR DESCRIPTION
**Pull request by jgtavarez**
I eliminated the values _(0,1)_ that I passed through parameters to determine if the player won or not, and replaced them with Boolean values _(True)_ when the player wins and _(False)_ when the player loses, so that I can use them directly in the _(If)._

### CODE REVIEW

**Comment by angerimg** [comment]
Need more context on the PR description 🤔

**Comment by angerimg** [comment]
Can you put me as a `reviewer`?

**Comment by jgtavarez** [comment]
@angerimg but I need you to be a collaborator to be able to put you as a reviewer, but you still do not accept the invitation.

**Comment by angerimg** [comment]
@JuanGabriel2960 omg let me see

**Comment by jgtavarez** [comment]
I sent you the invitation to collaborators, to later be a reviewer.

**Comment by angerimg** [comment]
done!

**Comment by jgtavarez** [comment]
You are already a **reviewer**, so point out what mistakes I made in this PR, to fix them.

**Comment by jgtavarez** [comment]
@angerimg  
Can i already merge this pull request to continue with the last one?

**Review by angerimg — APPROVED** [review]

**Pull request merged**
